name: Generate GitHub Snake ğŸ


on:
  workflow_dispatch:  
  schedule:
    - cron: "0 0 * * *" 

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1ï¸âƒ£ Checkout della repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2ï¸âƒ£ Genera Snake SVG
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: GiuseppeLiGioi  
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark
            output/github-snake-ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
